version: '3'

services:

  pcmz-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pcmzroot
      - MYSQL_DATABASE=InzDb
      - MYSQL_USER=pcmz-user
      - MYSQL_PASSWORD=pcmzpassword
    networks:
      - pcmz-net
    ports:
      - 3307:3306

  pcmz-main:
    build: .
    restart: on-failure
    networks:
      - pcmz-net
    ports:
      - 8090:8080
    environment:
      - DATABASE_HOST=pcmz-mysql
      - DATABASE_USER=pcmz-user
      - DATABASE_PASSWORD=pcmzpassword
      - DATABASE_NAME=InzDb
      - DATABASE_PORT=3307

networks:
  pcmz-net:
    driver: bridge

